In [1]:
import numpy as np

1. Array Creation & Attributes

In [2]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print("My Array:\n", my_array)

print("\nNumber of Dimensions (ndim):", my_array.ndim)
print("Shape of Array:", my_array.shape)
print("Data Type (dtype):", my_array.dtype)
print()

My Array:
 [[1 2 3]
 [4 5 6]]

Number of Dimensions (ndim): 2
Shape of Array: (2, 3)
Data Type (dtype): int32



2. Creating Arrays with Zeros and Ones

In [3]:
# ---------------------------------------------------------
# Note: It is best practice to use a tuple () for the shape
# ---------------------------------------------------------
print("1D Zeros Array:\n", np.zeros(4))          # 1D array of 4 elements, all will be 0
print("2D Zeros Array:\n", np.zeros((4, 4)))     # 4x4 2D matrix of zeros
print("3D Zeros Array:\n", np.zeros((4, 4, 4)))  # 4x4x4 3D matrix of zeros

print("\n1D Ones Array:\n", np.ones(4))          # 1D array of 4 elements, all will be 1
print("2D Ones Array:\n", np.ones((4, 4)))       # 4x4 2D matrix of ones
print("3D Ones Array:\n", np.ones((4, 4, 4)))    # 4x4x4 3D matrix of ones

1D Zeros Array:
 [0. 0. 0. 0.]
2D Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
3D Zeros Array:
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

1D Ones Array:
 [1. 1. 1. 1.]
2D Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
3D Ones Array:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


3. arange and Identity Array (Eye)

In [4]:
# np.arange(10) generates a sequence of numbers from 0 to 9
print("\nArange Array (0 to 9):\n", np.arange(10))

# np.eye(3) creates a 3x3 square matrix where the main diagonal is 1, and everything else is 0
print("\nIdentity Array (Eye):\n", np.eye(3))


Arange Array (0 to 9):
 [0 1 2 3 4 5 6 7 8 9]

Identity Array (Eye):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Indexing & Slicing

In [5]:
arr = np.array([10, 20, 30, 40, 50])

# Indexing: Extracting a specific element (counting starts at 0)
print("\nElement at index 2:", arr[2])

# Slicing: Extracting a range [start:end] (the 'end' index is excluded)
print("Sliced Array (0 to 2):", arr[0:3])


Element at index 2: 30
Sliced Array (0 to 2): [10 20 30]


5. Copying Arrays (Safe copy vs Assignment)

In [6]:
A = np.array([1, 2, 3])

# np.copy() creates a fresh, completely independent copy of the array
copy_array = np.copy(A)

# To prove they are separate, let's modify the first element of the copy
copy_array[0] = 100

print("\nOriginal Array 'A':", A)
print("Modified 'copy_array':", copy_array)


Original Array 'A': [1 2 3]
Modified 'copy_array': [100   2   3]


6. Array Join (Concatenation)

In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# We pass the arrays we want to join as a tuple (arr1, arr2)
joined_arr = np.concatenate((arr1, arr2))
print("Joined Array:", joined_arr)

Joined Array: [1 2 3 4 5 6]


7. Array Split

In [8]:
large_arr = np.array([1, 2, 3, 4, 5, 6])

# Splitting the array into 3 equal parts
split_arrays = np.array_split(large_arr, 3)
print("\nSplit Arrays:")
print(split_arrays[0])
print(split_arrays[1])
print(split_arrays[2])


Split Arrays:
[1 2]
[3 4]
[5 6]


8. Array Search

In [9]:
search_arr = np.array([10, 20, 30, 40, 30, 50])

# Searching for the value '30'
# It will return the index positions where 30 is found
result = np.where(search_arr == 30)
print("\nIndex positions of 30:", result[0])


Index positions of 30: [2 4]


9. Array Sort

In [10]:
unsorted_arr = np.array([3, 1, 5, 2, 4])

# Sorting the array in ascending order
sorted_arr = np.sort(unsorted_arr)
print("\nSorted Array:", sorted_arr)


Sorted Array: [1 2 3 4 5]
